- name: Installing Nginx server
  ansible.builtin.yum:
    name: nginx
    state: latest
- name: Starting Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
- name: Starting Nginx
  ansible.builtin.systemd:
    name: nginx
    state: stopped