- name: Frontend service
  hosts: APP
  become: true
  tasks:
    - name: Installing Nginx server
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: Starting Nginx
      ansible.builtin.systemd:
        name: Nginx
        state: Started
        enabled: yes
