- name: Frontend service
  hosts: WEB
  become: true
  tasks:
    - name: Installing Nginx server
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: Starting Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
- name: Frontend service
  hosts: APP
  become: true
  roles:
    - sample