- name: some playbook
  hosts: localhost
  become: true
  tasks:
    - name: installing nginx service
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: starting nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
    - name: starting nginx
      ansible.builtin.systemd:
        name: nginx
        state: stopped